import { NextRequest, NextResponse } from 'next/server';
import { withAuth } from '@/lib/middleware';
import { queryOne, query } from '@/lib/db';
import { sendEmail } from '@/lib/email';

async function handlePost(
  req: NextRequest,
  userId: string,
  context: { params: Promise<{ id: string }> }
) {
  const params = await context.params;
  try {
    const body = await req.json();
    const { month, year } = body;

    if (!month || !year) {
      return NextResponse.json(
        { success: false, error: 'Month and year are required' },
        { status: 400 }
      );
    }

    // Get employee
    const employee = await queryOne('SELECT * FROM employees WHERE id = ?', [params.id]);
    if (!employee) {
      return NextResponse.json(
        { success: false, error: 'Employee not found' },
        { status: 404 }
      );
    }

    // Get performance data
    const performance = await queryOne(
      'SELECT * FROM employee_performance WHERE employee_id = ? AND month = ? AND year = ?',
      [params.id, parseInt(month), parseInt(year)]
    );

    if (!performance) {
      return NextResponse.json(
        { success: false, error: 'Performance data not found for this month' },
        { status: 404 }
      );
    }

    // Get attendance data for the month
    const attendanceRecords = await query(
      `SELECT * FROM employee_attendance 
       WHERE employee_id = ? 
       AND YEAR(date) = ? 
       AND MONTH(date) = ? 
       ORDER BY date ASC`,
      [params.id, parseInt(year), parseInt(month)]
    );

    const totalDays = new Date(parseInt(year), parseInt(month), 0).getDate();
    const presentDays = attendanceRecords.filter((r: any) => r.status === 'PRESENT').length;
    const absentDays = attendanceRecords.filter((r: any) => r.status === 'ABSENT').length;
    const leaveDays = attendanceRecords.filter((r: any) => r.status === 'LEAVE').length;

    // Convert all scores to numbers (they might come as strings from DB)
    const overallScore = parseFloat(performance.overall_score) || 0;
    const attendanceScore = parseFloat(performance.attendance_score) || 0;
    const productivityScore = parseFloat(performance.productivity_score) || 0;
    const learningScore = parseFloat(performance.learning_score) || 0;
    const communicationScore = parseFloat(performance.communication_score) || 0;
    const teamworkScore = parseFloat(performance.teamwork_score) || 0;
    const initiativeScore = parseFloat(performance.initiative_score) || 0;

    const stats = {
      month: new Date(parseInt(year), parseInt(month) - 1).toLocaleString('en-US', { month: 'long' }),
      year: parseInt(year),
      totalDays,
      presentDays,
      absentDays,
      leaveDays,
    };

    // Generate performance report HTML
    const reportHtml = generatePerformanceReportHTML(employee, {
      ...performance,
      overall_score: overallScore,
      attendance_score: attendanceScore,
      productivity_score: productivityScore,
      learning_score: learningScore,
      communication_score: communicationScore,
      teamwork_score: teamworkScore,
      initiative_score: initiativeScore,
    }, stats);

    // Send email
    if (!employee.email) {
      return NextResponse.json(
        { success: false, error: 'Employee email not found' },
        { status: 400 }
      );
    }

    // Generate plain text version for email
    const textVersion = `
Performance Report - ${stats.month} ${stats.year}

Employee Information:
Name: ${employee.name}
Employee ID: ${employee.employee_id}
Designation: ${employee.designation}
Department: ${employee.department || 'N/A'}

Overall Score: ${overallScore.toFixed(1)}%

Performance Metrics:
- Attendance: ${attendanceScore.toFixed(1)}%
- Productivity: ${productivityScore.toFixed(1)}%
- Willingness to Learn: ${learningScore.toFixed(1)}%
- Communication: ${communicationScore.toFixed(1)}%
- Teamwork: ${teamworkScore.toFixed(1)}%
- Initiative: ${initiativeScore.toFixed(1)}%

Attendance Summary:
- Present Days: ${stats.presentDays}
- Absent Days: ${stats.absentDays}
- Leave Days: ${stats.leaveDays}
- Total Days: ${stats.totalDays}

${performance.comments ? `Comments:\n${performance.comments}` : ''}

---
This is an automated performance report generated by ${process.env.APP_NAME || 'Admin Panel'}
    `.trim();

    const emailResult = await sendEmail({
      to: employee.email,
      subject: `Performance Report - ${stats.month} ${stats.year}`,
      html: reportHtml,
      text: textVersion,
    });

    if (emailResult.success) {
      return NextResponse.json({
        success: true,
        message: 'Performance report sent successfully',
      });
    } else {
      console.error('Email sending failed:', emailResult.error);
      return NextResponse.json(
        { success: false, error: emailResult.error || 'Failed to send email' },
        { status: 500 }
      );
    }
  } catch (error: any) {
    console.error('Send performance report error:', error);
    return NextResponse.json(
      { success: false, error: error.message || 'Failed to send performance report' },
      { status: 500 }
    );
  }
}

function generatePerformanceReportHTML(
  employee: any,
  performance: any,
  stats: { month: string; year: number; totalDays: number; presentDays: number; absentDays: number; leaveDays: number }
): string {
  const getScoreColor = (score: number) => {
    if (score >= 80) return '#10b981'; // Green
    if (score >= 60) return '#f59e0b'; // Yellow
    return '#ef4444'; // Red
  };

  const getScoreLabel = (score: number) => {
    if (score >= 90) return 'Excellent';
    if (score >= 80) return 'Very Good';
    if (score >= 70) return 'Good';
    if (score >= 60) return 'Satisfactory';
    return 'Needs Improvement';
  };

  const overallScore = parseFloat(performance.overall_score) || 0;
  const attendanceScore = parseFloat(performance.attendance_score) || 0;
  const productivityScore = parseFloat(performance.productivity_score) || 0;
  const learningScore = parseFloat(performance.learning_score) || 0;
  const communicationScore = parseFloat(performance.communication_score) || 0;
  const teamworkScore = parseFloat(performance.teamwork_score) || 0;
  const initiativeScore = parseFloat(performance.initiative_score) || 0;

  return `
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <title>Performance Report - ${stats.month} ${stats.year}</title>
    </head>
    <body style="margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; background-color: #f3f4f6; line-height: 1.6; color: #1f2937;">
      <table role="presentation" style="width: 100%; border-collapse: collapse; background-color: #f3f4f6; padding: 20px 0;">
        <tr>
          <td align="center" style="padding: 20px 0;">
            <table role="presentation" style="width: 600px; max-width: 100%; border-collapse: collapse; background-color: #ffffff; border-radius: 8px; overflow: hidden; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);">
              
              <!-- Header -->
              <tr>
                <td style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 40px 30px; text-align: center;">
                  <h1 style="margin: 0; color: #ffffff; font-size: 28px; font-weight: 700; letter-spacing: -0.5px;">Performance Report</h1>
                  <p style="margin: 10px 0 0 0; color: #e0e7ff; font-size: 16px; font-weight: 400;">${stats.month} ${stats.year}</p>
                </td>
              </tr>

              <!-- Employee Info Section -->
              <tr>
                <td style="padding: 30px; background-color: #ffffff;">
                  <div style="background-color: #f9fafb; border-radius: 8px; padding: 20px; margin-bottom: 25px;">
                    <h2 style="margin: 0 0 15px 0; color: #111827; font-size: 18px; font-weight: 600; border-bottom: 2px solid #e5e7eb; padding-bottom: 10px;">Employee Information</h2>
                    <table role="presentation" style="width: 100%; border-collapse: collapse;">
                      <tr>
                        <td style="padding: 8px 0; color: #6b7280; font-size: 14px; width: 140px;"><strong>Name:</strong></td>
                        <td style="padding: 8px 0; color: #111827; font-size: 14px; font-weight: 500;">${employee.name}</td>
                      </tr>
                      <tr>
                        <td style="padding: 8px 0; color: #6b7280; font-size: 14px;"><strong>Employee ID:</strong></td>
                        <td style="padding: 8px 0; color: #111827; font-size: 14px; font-weight: 500;">${employee.employee_id}</td>
                      </tr>
                      <tr>
                        <td style="padding: 8px 0; color: #6b7280; font-size: 14px;"><strong>Designation:</strong></td>
                        <td style="padding: 8px 0; color: #111827; font-size: 14px; font-weight: 500;">${employee.designation}</td>
                      </tr>
                      <tr>
                        <td style="padding: 8px 0; color: #6b7280; font-size: 14px;"><strong>Department:</strong></td>
                        <td style="padding: 8px 0; color: #111827; font-size: 14px; font-weight: 500;">${employee.department || 'N/A'}</td>
                      </tr>
                    </table>
                  </div>

                  <!-- Overall Score -->
                  <div style="text-align: center; margin: 30px 0; padding: 30px; background: linear-gradient(135deg, #f0f9ff 0%, #e0f2fe 100%); border-radius: 12px; border: 2px solid ${getScoreColor(overallScore)};">
                    <div style="font-size: 56px; font-weight: 700; color: ${getScoreColor(overallScore)}; margin: 0 0 10px 0; line-height: 1;">
                      ${overallScore.toFixed(1)}%
                    </div>
                    <div style="font-size: 20px; font-weight: 600; color: ${getScoreColor(overallScore)}; margin: 0;">
                      ${getScoreLabel(overallScore)}
                    </div>
                  </div>

                  <!-- Performance Metrics -->
                  <h2 style="margin: 30px 0 20px 0; color: #111827; font-size: 20px; font-weight: 600;">Performance Metrics</h2>
                  
                  ${generateScoreCard('Attendance', attendanceScore, getScoreColor(attendanceScore), '20%')}
                  ${generateScoreCard('Productivity', productivityScore, getScoreColor(productivityScore), '25%')}
                  ${generateScoreCard('Willingness to Learn', learningScore, getScoreColor(learningScore), '15%')}
                  ${generateScoreCard('Communication', communicationScore, getScoreColor(communicationScore), '15%')}
                  ${generateScoreCard('Teamwork', teamworkScore, getScoreColor(teamworkScore), '15%')}
                  ${generateScoreCard('Initiative', initiativeScore, getScoreColor(initiativeScore), '10%')}

                  <!-- Attendance Summary -->
                  <h2 style="margin: 35px 0 20px 0; color: #111827; font-size: 20px; font-weight: 600;">Attendance Summary</h2>
                  <table role="presentation" style="width: 100%; border-collapse: collapse; margin-bottom: 25px;">
                    <tr>
                      <td style="width: 25%; padding: 15px; background-color: #f0fdf4; border-radius: 8px; text-align: center; border: 1px solid #dcfce7;">
                        <div style="font-size: 28px; font-weight: 700; color: #16a34a; margin-bottom: 5px;">${stats.presentDays}</div>
                        <div style="font-size: 12px; color: #6b7280; text-transform: uppercase; letter-spacing: 0.5px;">Present</div>
                      </td>
                      <td style="width: 25%; padding: 15px; background-color: #fef2f2; border-radius: 8px; text-align: center; border: 1px solid #fecaca;">
                        <div style="font-size: 28px; font-weight: 700; color: #dc2626; margin-bottom: 5px;">${stats.absentDays}</div>
                        <div style="font-size: 12px; color: #6b7280; text-transform: uppercase; letter-spacing: 0.5px;">Absent</div>
                      </td>
                      <td style="width: 25%; padding: 15px; background-color: #fffbeb; border-radius: 8px; text-align: center; border: 1px solid #fde68a;">
                        <div style="font-size: 28px; font-weight: 700; color: #d97706; margin-bottom: 5px;">${stats.leaveDays}</div>
                        <div style="font-size: 12px; color: #6b7280; text-transform: uppercase; letter-spacing: 0.5px;">Leave</div>
                      </td>
                      <td style="width: 25%; padding: 15px; background-color: #f9fafb; border-radius: 8px; text-align: center; border: 1px solid #e5e7eb;">
                        <div style="font-size: 28px; font-weight: 700; color: #374151; margin-bottom: 5px;">${stats.totalDays}</div>
                        <div style="font-size: 12px; color: #6b7280; text-transform: uppercase; letter-spacing: 0.5px;">Total</div>
                      </td>
                    </tr>
                  </table>

                  ${performance.comments ? `
                  <!-- Comments Section -->
                  <div style="background-color: #eff6ff; border-left: 4px solid #3b82f6; border-radius: 8px; padding: 20px; margin-top: 25px;">
                    <h3 style="margin: 0 0 12px 0; color: #1e40af; font-size: 16px; font-weight: 600;">Comments & Feedback</h3>
                    <p style="margin: 0; color: #1f2937; font-size: 14px; white-space: pre-wrap; line-height: 1.7;">${performance.comments}</p>
                  </div>
                  ` : ''}
                </td>
              </tr>

              <!-- Footer -->
              <tr>
                <td style="padding: 25px 30px; background-color: #f9fafb; border-top: 1px solid #e5e7eb; text-align: center;">
                  <p style="margin: 0; color: #6b7280; font-size: 12px; line-height: 1.5;">
                    This is an automated performance report generated by<br>
                    <strong style="color: #374151;">${process.env.APP_NAME || 'Admin Panel'}</strong>
                  </p>
                  <p style="margin: 15px 0 0 0; color: #9ca3af; font-size: 11px;">
                    Please do not reply to this email. For questions, contact your HR department.
                  </p>
                </td>
              </tr>
            </table>
          </td>
        </tr>
      </table>
    </body>
    </html>
  `;
}

function generateScoreCard(label: string, score: number, color: string, weight: string): string {
  const scoreNum = parseFloat(score.toString()) || 0;
  const percentage = Math.min(100, Math.max(0, scoreNum));
  
  return `
    <div style="background-color: #ffffff; border: 1px solid #e5e7eb; border-radius: 8px; padding: 18px; margin-bottom: 15px; box-shadow: 0 1px 3px rgba(0, 0, 0, 0.05);">
      <table role="presentation" style="width: 100%; border-collapse: collapse;">
        <tr>
          <td style="padding: 0;">
            <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 12px;">
              <div>
                <span style="color: #111827; font-size: 15px; font-weight: 600;">${label}</span>
                <span style="color: #9ca3af; font-size: 12px; margin-left: 8px;">(Weight: ${weight})</span>
              </div>
              <span style="color: ${color}; font-size: 20px; font-weight: 700;">${scoreNum.toFixed(1)}%</span>
            </div>
            <div style="background-color: #f3f4f6; border-radius: 10px; height: 24px; overflow: hidden; position: relative;">
              <div style="background: linear-gradient(90deg, ${color} 0%, ${color}dd 100%); width: ${percentage}%; height: 100%; border-radius: 10px; display: flex; align-items: center; justify-content: ${percentage > 15 ? 'flex-end' : 'center'}; padding-right: ${percentage > 15 ? '8px' : '0'}; transition: width 0.3s ease;">
                ${percentage > 15 ? `<span style="color: #ffffff; font-size: 11px; font-weight: 600;">${Math.round(percentage)}%</span>` : ''}
              </div>
            </div>
          </td>
        </tr>
      </table>
    </div>
  `;
}

export const POST = withAuth(handlePost);
